sudo: required

services:
- docker
language: bash

script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build --tag arnaudra/docker-cups-canon:build .
# test image
#- docker run arnaudr/docker-cups-canon

after_script:
- docker images

before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
deploy:
  provider: script
  script: docker push arnaudra/docker-cups-canon
  on:
   branch: master